server:
  port: 8083

spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flowstock}
    username: ${DB_USERNAME:ashishbhardwaj}
    password: ${DB_PASSWORD:wareflow_dev}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: warehouse
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: warehouse
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
